config/routes.rb
Rails.application.routes.draw do
  root 'lists#index'
  resources :lists
  resources :items

end

app/models/item.rb
class Item < ActiveRecord::Base
  #:name :description :priority :completed
  belongs_to :list
end

app/models/list.rb
class List < ActiveRecord::Base
  #name
  has_many :items, dependent: :destroy
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/items_controller.rb
class ItemsController < ApplicationController
  # def index
  # end

  def show
    @item = Item.find(params[:id])

    @items_list = List.find(params[:list_id])
  end

  def new
    @item = Item.new

    @items_list = List.find(params[:list_id])
  end


  def create
    @item = Item.new(item_params)
    if @item.save
       redirect_to list_path(@item.list_id)
    else
      render :new
    end
  end


  def edit

    @item = Item.find(params[:id])

  end

  def update

    @item = Item.find(params[:id])
    id = @item.list_id

    if @item.update(item_params)
      redirect_to list_path(@item.list_id)

    else
      render :edit
    end
  end

  def destroy
    @item = Item.find(params[:id])

    @item.destroy
    redirect_to list_path(@item.list_id)
  end

  private
  def item_params
    params.require(:item).permit(:name,:description,:priority,:list_id, :completed)
  end
end

app/controllers/lists_controller.rb
class ListsController < ApplicationController

  def index
      @lists = List.all
      #binding.pry
  end
  def new
    @list = List.new
  end

  def show
    @list = List.find(params[:id])
    @items = @list.items
  end

  def create
    @list = List.new list_params
    if @list.save
      redirect_to root_path
    else
      # TODO: display errors
      render :new
    end
  end


  def edit
    @list = List.find(params[:id])
  end

  def update
    @list = List.find(params[:id])
    if @list.update(list_params)
      redirect_to root_path
    else
      # TODO: display errors
      render :edit
    end
  end

  def destroy
    @list = List.find(params[:id])
    @list.destroy
    redirect_to root_path
  end

  private
  def list_params
    params.require(:list).permit(:name)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/items_helper.rb
module ItemsHelper
end

app/helpers/lists_helper.rb
module ListsHelper
end

app/views/items/edit.html.erb
<h1>Edit Item</h1>

<%= render partial: 'layouts/item_form' %>

app/views/items/new.html.erb
<h1>New Item for <%= link_to @items_list.name, list_path(@items_list)%> </h1>

<%= render partial: 'layouts/item_form' %>

app/views/items/show.html.erb
<h1><%= "Item: #{@item.name}, In List: "%>

  <%= link_to @items_list.name, list_path(@items_list) %></h1>
<label for="">description:</label>
<p><%= @item.description %></p>
<label for="">completed:</label>
<p><%= @item.completed %></p>
<hr>
<label for="">Priority:</label>
<p><%= @item.priority %></p>
 <!-- form hiddin field-->

<hr>
<%= link_to '&#9998;', edit_item_path(@item,:list_id => @item.list_id) %>

<br>
<%= button_to 'Delete', item_path(@item), method: :delete,
              data:{confirm: 'Really delete this item'} %>

app/views/layouts/_item_form.html.erb
<%= form_for @item do |f| %>

    <% if @item.list_id != nil && @item.list_id > 0 %>
        <%= f.hidden_field :list_id, :value => @item.list_id %>
    <% else %>

         <%= f.hidden_field :list_id, :value => params[:list_id] %>
    <% end %>
    <hr>

    <%= f.label :name %>
    <%= f.text_field  :name%>
    <br>

    <%= f.label :description %>
    <%= f.text_area :description%>
    <br>
    <%= f.label :completed%>
    <%= f.check_box :completed%>
    <br>


    <br>
    <%= f.label :priority%>
    <%= f.select :priority, [1,2,3,4,5,6,7,8,9,10] %>
    <br>
    <%= f.submit %>
<% end %>

app/views/layouts/_list_form.erb
<h1><%=@list.name %> </h1>
<%= form_for @list do |f| %>
    <%= f.label :name %>
    <%= f.text_field :name %>

    <%=f.submit %>
<% end %>

app/views/layouts/_nav_bar.html.erb
<%= link_to 'Lists', root_path %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>TheRealTodoList</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
  <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.6/css/bootstrap.min.css">
</head>
<body>
<%= render partial: "layouts/nav_bar" %>
<div class ="container">
  <%= yield %>
</div>


</body>
</html>

app/views/lists/edit.html.erb
<%= render partial: 'layouts/list_form' %>

app/views/lists/index.html.erb
<div class="big">Lists
  <span class="small"><%= link_to 'New List +', new_list_path %></span>
</div>

<br>

<br>
<% if @lists.any? %>
    <% @lists.each do |list| %>
        <h1 class="list-name" ><%= link_to "#{list.name}.", list_path(list)%>
        </h1>


        <!--<% if list.items.any? %>-->

            <!--<% list.items.each do |item| %>-->
                <!--<h4><%= item.name %></h4>-->
            <!--<% end %>-->

        <!--<% else %>-->
            <!--<p>no items</p>-->
        <!--<% end %>-->

    <% end %>
    <%else %>
<h3>No lists</h3>
<% end %>

app/views/lists/new.html.erb
<h1>Gots todo....</h1>
<%= render partial: 'layouts/list_form' %>

app/views/lists/show.html.erb
<div class="big"><%= @list.name %>
  <span class="small">
    <%= link_to "edit", edit_list_path(@list, :list_id => @list.id)%>
    <%=  link_to 'X',list_path(@list,:list_id => @list.id),
                 method: :delete, data:{confirm: 'Really delete this item'} %>
   </span>
</div>
<% if @items.any? %>
    <br>
    <% @items.each do |item| %>
        <div class="big">
          <%= link_to "-#{item.name}", item_path(item,:list_id => @list.id) %>

          <span class="small"><%= link_to 'Edit', edit_item_path(item,:list_id => @list.id) %>
            <%= link_to 'X', item_path(item,:list_id => @list.id),
                        method: :delete, data:{confirm: 'Really delete this item'} %>
          </span>
        </div>
        <br>


        <br>
    <% end %>
<% else %>
    <p>No items in list</p>

<% end %>
<%= link_to 'Add item', new_item_path(:list_id => @list.id) %>